# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glids < Formula
  desc "glids - GitLab ID Lister"
  homepage "https://github.com/bboles/glids"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bboles/glids/releases/download/v0.2.5/glids_Darwin_x86_64.tar.gz"
      sha256 "dc67347388dc5183d4c9bde0684f69f26baf7ca136ec94d271ef4a6ddd8174f8"

      def install
        bin.install "glids"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bboles/glids/releases/download/v0.2.5/glids_Darwin_arm64.tar.gz"
      sha256 "67444bf33e041fd751232183147ca2cf565ad102db54ad661b473d9b65b50cc4"

      def install
        bin.install "glids"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/bboles/glids/releases/download/v0.2.5/glids_Linux_x86_64.tar.gz"
      sha256 "55b26b36efbf6a2eee9ddca39efe2391abea495685e5b009d2feec55ffb3d6e5"
      def install
        bin.install "glids"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/bboles/glids/releases/download/v0.2.5/glids_Linux_arm64.tar.gz"
      sha256 "97e7f2bdd1e7029f6d2b352246dc3c377c8839475cc35b75e5facfdf351035fe"
      def install
        bin.install "glids"
      end
    end
  end

  test do
    system "#{bin}/glids --version"
  end
end
