# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glids < Formula
  desc "glids - GitLab ID Lister"
  homepage "https://github.com/bboles/glids"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bboles/glids/releases/download/v0.2.0/glids_Darwin_x86_64.tar.gz"
      sha256 "e52fa1d8aba23e4b38a90c6d7c7ddd673ef28adb9880cdb29a0d84fc89277f43"

      def install
        bin.install "glids"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bboles/glids/releases/download/v0.2.0/glids_Darwin_arm64.tar.gz"
      sha256 "b743f9dd65203c2b85cc4e2a015696f9d4176172dc3e634d51c85b73953de4a7"

      def install
        bin.install "glids"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/bboles/glids/releases/download/v0.2.0/glids_Linux_x86_64.tar.gz"
      sha256 "7a10f1bdb308d1a2bfda20236794626ccbeff4ede1738d9681e34fa9f3fd7369"
      def install
        bin.install "glids"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/bboles/glids/releases/download/v0.2.0/glids_Linux_arm64.tar.gz"
      sha256 "074477786e5a8640468cf4da728c0998e15c75f992fb9961bd60b4301c7234e4"
      def install
        bin.install "glids"
      end
    end
  end

  test do
    system "#{bin}/glids --version"
  end
end
